import static colors.colors.ANSI_GREEN;
import static colors.colors.ANSI_RESET;
import static colors.colors.ANSI_YELLOW;
import java.awt.Color;

import java.util.List;
import javax.swing.JOptionPane;


public class softwareDownload extends javax.swing.JFrame {
    
    database db = new database();
    ClienteMulticast ClienteMulticast = new ClienteMulticast(db);
    ClienteMulticastCheckList ClienteMulticastCheck = new ClienteMulticastCheckList(db);
    ClienteRMI ClienteRMI = new ClienteRMI(db, this);
    ClienteUnicast ClienteUnicast = new ClienteUnicast(db, this);

    /**
     * Creates new form Client
     */
    public softwareDownload() {
        initComponents();
        lblResult.setVisible(false);        
        
        ClienteMulticast.start();
        ClienteMulticastCheck.start();
        ClienteRMI.start();
        ClienteUnicast.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        inputFileName = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        lblResult = new javax.swing.JLabel();
        btnDownload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Busqueda de archivos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        inputFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileNameActionPerformed(evt);
            }
        });
        getContentPane().add(inputFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 30));

        btnBuscar.setFont(new java.awt.Font("VL Gothic", 0, 13)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 40));
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 330, 300, 20));

        lblResult.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblResult.setForeground(new java.awt.Color(102, 255, 102));
        lblResult.setText("Listo para buscar...");
        getContentPane().add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 200, 40));

        btnDownload.setText("Descargar");
        btnDownload.setEnabled(false);
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        getContentPane().add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, 60));

        jLabel1.setText("Ingresa el nombre del archivo que deseas descargar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, -1));

        jLabel3.setText(" con extención");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 65, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       //Verificar que en la db haya al menos 1 servidor
       List<serverData> ServersList = db.getServersList();
       if(ServersList.size() != 0){
           ClienteRMI.searchFile(inputFileName.getText());
       }else{
           JOptionPane.showMessageDialog(null, "No hay ningun servidor disponible", "Busqueda", JOptionPane.WARNING_MESSAGE);
       }
      
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        System.out.println("Se descargara: "+db.getFileFound().getPath().toString() + " de: "+db.getServerFileFound());
        //Nos conectamos
        ClienteUnicast.connectWithServer();
        ClienteUnicast.downloadFile();
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void inputFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFileNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(softwareDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(softwareDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(softwareDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(softwareDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new softwareDownload().setVisible(true);
            }
        });
    }
    
    public void changeResultLabel(boolean b, String text){
        if(b){
            lblResult.setForeground(Color.green);
        }else{
            lblResult.setForeground(Color.red);
        }
        lblResult.setText(text);
        lblResult.setVisible(true);
    }
    
    public void changeDownload(boolean b){
        btnDownload.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDownload;
    private javax.swing.JTextField inputFileName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResult;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables


    void setProgressBar(int porciento_recibido) {
        progressBar.setValue(porciento_recibido);
        progressBar.setStringPainted(true);
    }
}
